name: Releases

on:
  push:
    tags:
      - "*"

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      CPATH: C:\Program Files (x86)\WinFsp\inc\fuse
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
      - name: Install WinFsp
        run: choco install winfsp --pre
      - name: Build Dsfs
        run: go build -o dsfs.exe -ldflags="-s -w"
      - name: Upload Dsfs
        uses: actions/upload-artifact@v3
        with:
          name: dsfs-windows
          path: dsfs.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
      - name: Install libfuse
        run: sudo apt-get install -y libfuse-dev
      - name: Build Dsfs
        run: go build -o dsfs -ldflags="-s -w"
      - name: Upload Dsfs
        uses: actions/upload-artifact@v3
        with:
          name: dsfs-linux
          path: dsfs

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
      - name: Install macfuse
        run: brew install macfuse
      - name: Build Dsfs
        run: go build -o dsfs -ldflags="-s -w"
      - name: Upload Dsfs
        uses: actions/upload-artifact@v3
        with:
          name: dsfs-macos
          path: dsfs

  release:
    needs: [build-windows, build-linux, build-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install zip
        run: sudo apt-get install -y zip
      - name: Download Windows artifact
        uses: actions/download-artifact@v3
        with:
          name: dsfs-windows
      - name: Zip Windows release
        run: zip -r dsfs_${{github.ref_name}}_windows_amd64.zip dsfs.exe README.md LICENSE
      - name: Download Linux artifact
        uses: actions/download-artifact@v3
        with:
          name: dsfs-linux
      - name: Tar Gzip Linux release
        run: tar -czvf dsfs_${{github.ref_name}}_linux_amd64.tar.gz dsfs README.md LICENSE
      - name: Download macOS artifact
        uses: actions/download-artifact@v3
        with:
          name: dsfs-macos
      - name: Tar Gzip macOS release
        run: tar -czvf dsfs_${{github.ref_name}}_darwin_amd64.tar.gz dsfs README.md LICENSE
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dsfs_${{github.ref_name}}_windows_amd64.zip
            dsfs_${{github.ref_name}}_linux_amd64.tar.gz
            dsfs_${{github.ref_name}}_darwin_amd64.tar.gz
